language: java
jdk:
  - openjdk11

script:
  - mvn clean install

deploy:
  provider: script
  script: mvn clean deploy -DskipTests
  on:
    branch: main

after_deploy:
  - ARTIFACT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - echo "Artifact Version: $ARTIFACT_VERSION"
  - echo "artifact_version=$ARTIFACT_VERSION" >> $GITHUB_ENV
